// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_outbox.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const enqueueOutboxEvent = `-- name: EnqueueOutboxEvent :exec
INSERT INTO ops.outbox (
  tenant_id,
  id,
  event_type,
  event_version,
  correlation_id,
  payload,
  occurred_at
) VALUES (
  $1::uuid,
  $2::uuid,
  $3::text,
  $4::int,
  $5::uuid,
  $6::jsonb,
  $7::timestamptz
)
`

type EnqueueOutboxEventParams struct {
	TenantID      pgtype.UUID
	EventID       pgtype.UUID
	EventType     string
	EventVersion  int32
	CorrelationID pgtype.UUID
	Payload       []byte
	OccurredAt    pgtype.Timestamptz
}

func (q *Queries) EnqueueOutboxEvent(ctx context.Context, arg EnqueueOutboxEventParams) error {
	_, err := q.db.Exec(ctx, enqueueOutboxEvent,
		arg.TenantID,
		arg.EventID,
		arg.EventType,
		arg.EventVersion,
		arg.CorrelationID,
		arg.Payload,
		arg.OccurredAt,
	)
	return err
}

const getAuditChainHead = `-- name: GetAuditChainHead :one
SELECT last_sequence, last_chain_hash
FROM audit.chain_heads
WHERE tenant_id = $1::uuid
`

type GetAuditChainHeadRow struct {
	LastSequence  int64
	LastChainHash []byte
}

func (q *Queries) GetAuditChainHead(ctx context.Context, tenantID pgtype.UUID) (GetAuditChainHeadRow, error) {
	row := q.db.QueryRow(ctx, getAuditChainHead, tenantID)
	var i GetAuditChainHeadRow
	err := row.Scan(&i.LastSequence, &i.LastChainHash)
	return i, err
}

const getAuditCheckpoint = `-- name: GetAuditCheckpoint :one
SELECT tenant_id, id, chain_sequence, chain_hash, statement_digest,
       algorithm, key_id, signature, signed_at
FROM audit.checkpoints
WHERE tenant_id = $1::uuid
  AND chain_sequence = $2::bigint
  AND key_id = $3::text
`

type GetAuditCheckpointParams struct {
	TenantID      pgtype.UUID
	ChainSequence int64
	KeyID         string
}

func (q *Queries) GetAuditCheckpoint(ctx context.Context, arg GetAuditCheckpointParams) (AuditCheckpoint, error) {
	row := q.db.QueryRow(ctx, getAuditCheckpoint, arg.TenantID, arg.ChainSequence, arg.KeyID)
	var i AuditCheckpoint
	err := row.Scan(
		&i.TenantID,
		&i.ID,
		&i.ChainSequence,
		&i.ChainHash,
		&i.StatementDigest,
		&i.Algorithm,
		&i.KeyID,
		&i.Signature,
		&i.SignedAt,
	)
	return i, err
}

const insertAuditCheckpoint = `-- name: InsertAuditCheckpoint :one
INSERT INTO audit.checkpoints (
  tenant_id,
  id,
  chain_sequence,
  chain_hash,
  statement_digest,
  algorithm,
  key_id,
  signature,
  signed_at
) VALUES (
  $1::uuid,
  $2::uuid,
  $3::bigint,
  $4::bytea,
  $5::bytea,
  $6::text,
  $7::text,
  $8::bytea,
  $9::timestamptz
)
ON CONFLICT (tenant_id, chain_sequence, key_id) DO NOTHING
RETURNING tenant_id, id, chain_sequence, chain_hash, statement_digest,
          algorithm, key_id, signature, signed_at
`

type InsertAuditCheckpointParams struct {
	TenantID        pgtype.UUID
	CheckpointID    pgtype.UUID
	ChainSequence   int64
	ChainHash       []byte
	StatementDigest []byte
	Algorithm       string
	KeyID           string
	Signature       []byte
	SignedAt        pgtype.Timestamptz
}

func (q *Queries) InsertAuditCheckpoint(ctx context.Context, arg InsertAuditCheckpointParams) (AuditCheckpoint, error) {
	row := q.db.QueryRow(ctx, insertAuditCheckpoint,
		arg.TenantID,
		arg.CheckpointID,
		arg.ChainSequence,
		arg.ChainHash,
		arg.StatementDigest,
		arg.Algorithm,
		arg.KeyID,
		arg.Signature,
		arg.SignedAt,
	)
	var i AuditCheckpoint
	err := row.Scan(
		&i.TenantID,
		&i.ID,
		&i.ChainSequence,
		&i.ChainHash,
		&i.StatementDigest,
		&i.Algorithm,
		&i.KeyID,
		&i.Signature,
		&i.SignedAt,
	)
	return i, err
}

const insertAuditEvent = `-- name: InsertAuditEvent :exec
INSERT INTO audit.events (
  tenant_id,
  id,
  actor_subject_id,
  event_type,
  action,
  decision,
  policy_version,
  correlation_id,
  safe_metadata,
  previous_hash,
  event_hash,
  occurred_at
) VALUES (
  $1::uuid,
  $2::uuid,
  $3::uuid,
  $4::text,
  $5::text,
  $6::text,
  $7::bigint,
  $8::uuid,
  $9::jsonb,
  $10::bytea,
  $11::bytea,
  $12::timestamptz
)
`

type InsertAuditEventParams struct {
	TenantID       pgtype.UUID
	EventID        pgtype.UUID
	ActorSubjectID pgtype.UUID
	EventType      string
	Action         string
	Decision       string
	PolicyVersion  int64
	CorrelationID  pgtype.UUID
	SafeMetadata   []byte
	PreviousHash   []byte
	EventHash      []byte
	OccurredAt     pgtype.Timestamptz
}

func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) error {
	_, err := q.db.Exec(ctx, insertAuditEvent,
		arg.TenantID,
		arg.EventID,
		arg.ActorSubjectID,
		arg.EventType,
		arg.Action,
		arg.Decision,
		arg.PolicyVersion,
		arg.CorrelationID,
		arg.SafeMetadata,
		arg.PreviousHash,
		arg.EventHash,
		arg.OccurredAt,
	)
	return err
}
