// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_outbox.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAuditEvent = `-- name: InsertAuditEvent :exec
INSERT INTO audit.events (
  tenant_id,
  id,
  actor_subject_id,
  event_type,
  action,
  decision,
  policy_version,
  correlation_id,
  safe_metadata,
  previous_hash,
  event_hash,
  occurred_at
) VALUES (
  $1::uuid,
  $2::uuid,
  $3::uuid,
  $4::text,
  $5::text,
  $6::text,
  $7::bigint,
  $8::uuid,
  $9::jsonb,
  $10::bytea,
  $11::bytea,
  $12::timestamptz
)
`

type InsertAuditEventParams struct {
	TenantID       pgtype.UUID
	ID             pgtype.UUID
	ActorSubjectID pgtype.UUID
	EventType      string
	Action         string
	Decision       string
	PolicyVersion  int64
	CorrelationID  pgtype.UUID
	SafeMetadata   []byte
	PreviousHash   []byte
	EventHash      []byte
	OccurredAt     pgtype.Timestamptz
}

func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) error {
	_, err := q.db.Exec(ctx, insertAuditEvent,
		arg.TenantID,
		arg.ID,
		arg.ActorSubjectID,
		arg.EventType,
		arg.Action,
		arg.Decision,
		arg.PolicyVersion,
		arg.CorrelationID,
		arg.SafeMetadata,
		arg.PreviousHash,
		arg.EventHash,
		arg.OccurredAt,
	)
	return err
}

const enqueueOutboxEvent = `-- name: EnqueueOutboxEvent :exec
INSERT INTO ops.outbox (
  tenant_id,
  id,
  event_type,
  event_version,
  correlation_id,
  payload,
  occurred_at
) VALUES (
  $1::uuid,
  $2::uuid,
  $3::text,
  $4::int,
  $5::uuid,
  $6::jsonb,
  $7::timestamptz
)
`

type EnqueueOutboxEventParams struct {
	TenantID      pgtype.UUID
	ID            pgtype.UUID
	EventType     string
	EventVersion  int32
	CorrelationID pgtype.UUID
	Payload       []byte
	OccurredAt    pgtype.Timestamptz
}

func (q *Queries) EnqueueOutboxEvent(ctx context.Context, arg EnqueueOutboxEventParams) error {
	_, err := q.db.Exec(ctx, enqueueOutboxEvent,
		arg.TenantID,
		arg.ID,
		arg.EventType,
		arg.EventVersion,
		arg.CorrelationID,
		arg.Payload,
		arg.OccurredAt,
	)
	return err
}
