// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeOIDCAuthorizationAttempt = `-- name: ConsumeOIDCAuthorizationAttempt :one
SELECT
  attempt.nonce_hash::bytea AS nonce_hash,
  attempt.pkce_verifier::text AS pkce_verifier,
  attempt.redirect_uri::text AS redirect_uri
FROM iam.consume_oidc_authorization_attempt($1::bytea) AS attempt(
  nonce_hash,
  pkce_verifier,
  redirect_uri
)
`

type ConsumeOIDCAuthorizationAttemptRow struct {
	NonceHash    []byte
	PkceVerifier string
	RedirectUri  string
}

func (q *Queries) ConsumeOIDCAuthorizationAttempt(ctx context.Context, stateHash []byte) (ConsumeOIDCAuthorizationAttemptRow, error) {
	row := q.db.QueryRow(ctx, consumeOIDCAuthorizationAttempt, stateHash)
	var i ConsumeOIDCAuthorizationAttemptRow
	err := row.Scan(&i.NonceHash, &i.PkceVerifier, &i.RedirectUri)
	return i, err
}

const createOIDCAuthorizationAttempt = `-- name: CreateOIDCAuthorizationAttempt :exec
SELECT iam.create_oidc_authorization_attempt(
  $1::bytea,
  $2::bytea,
  $3::text,
  $4::text,
  $5::timestamptz
)
`

type CreateOIDCAuthorizationAttemptParams struct {
	StateHash    []byte
	NonceHash    []byte
	PkceVerifier string
	RedirectUri  string
	ExpiresAt    pgtype.Timestamptz
}

func (q *Queries) CreateOIDCAuthorizationAttempt(ctx context.Context, arg CreateOIDCAuthorizationAttemptParams) error {
	_, err := q.db.Exec(ctx, createOIDCAuthorizationAttempt,
		arg.StateHash,
		arg.NonceHash,
		arg.PkceVerifier,
		arg.RedirectUri,
		arg.ExpiresAt,
	)
	return err
}

const createSession = `-- name: CreateSession :one
SELECT iam.create_session(
  $1::uuid,
  $2::uuid,
  $3::bytea,
  $4::bytea,
  $5::timestamptz
)::uuid AS session_id
`

type CreateSessionParams struct {
	SessionID        pgtype.UUID
	SubjectID        pgtype.UUID
	SessionTokenHash []byte
	CsrfTokenHash    []byte
	ExpiresAt        pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.SessionID,
		arg.SubjectID,
		arg.SessionTokenHash,
		arg.CsrfTokenHash,
		arg.ExpiresAt,
	)
	var session_id pgtype.UUID
	err := row.Scan(&session_id)
	return session_id, err
}

const getActiveSession = `-- name: GetActiveSession :one
SELECT
  active_session.id::uuid AS id,
  active_session.subject_id::uuid AS subject_id,
  active_session.csrf_token_hash::bytea AS csrf_token_hash,
  active_session.active_tenant_id::uuid AS active_tenant_id,
  active_session.active_workspace_id::uuid AS active_workspace_id,
  active_session.expires_at::timestamptz AS expires_at,
  active_session.rotated_at::timestamptz AS rotated_at
FROM iam.get_active_session($1::bytea) AS active_session(
  id,
  subject_id,
  csrf_token_hash,
  active_tenant_id,
  active_workspace_id,
  expires_at,
  rotated_at
)
`

type GetActiveSessionRow struct {
	ID                pgtype.UUID
	SubjectID         pgtype.UUID
	CsrfTokenHash     []byte
	ActiveTenantID    pgtype.UUID
	ActiveWorkspaceID pgtype.UUID
	ExpiresAt         pgtype.Timestamptz
	RotatedAt         pgtype.Timestamptz
}

func (q *Queries) GetActiveSession(ctx context.Context, sessionTokenHash []byte) (GetActiveSessionRow, error) {
	row := q.db.QueryRow(ctx, getActiveSession, sessionTokenHash)
	var i GetActiveSessionRow
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.CsrfTokenHash,
		&i.ActiveTenantID,
		&i.ActiveWorkspaceID,
		&i.ExpiresAt,
		&i.RotatedAt,
	)
	return i, err
}

const getSessionIdentity = `-- name: GetSessionIdentity :one
SELECT
  session_identity.id::uuid AS id,
  session_identity.display_name::text AS display_name
FROM iam.get_session_identity($1::bytea) AS session_identity(
  id,
  display_name
)
`

type GetSessionIdentityRow struct {
	ID          pgtype.UUID
	DisplayName string
}

func (q *Queries) GetSessionIdentity(ctx context.Context, sessionTokenHash []byte) (GetSessionIdentityRow, error) {
	row := q.db.QueryRow(ctx, getSessionIdentity, sessionTokenHash)
	var i GetSessionIdentityRow
	err := row.Scan(&i.ID, &i.DisplayName)
	return i, err
}

const listSessionTenants = `-- name: ListSessionTenants :many
SELECT
  session_tenant.tenant_id::uuid AS tenant_id,
  session_tenant.slug::text AS slug,
  session_tenant.display_name::text AS display_name,
  session_tenant.status::text AS status,
  session_tenant.starter_role::text AS starter_role
FROM iam.list_session_tenants($1::bytea) AS session_tenant(
  tenant_id,
  slug,
  display_name,
  status,
  starter_role
)
`

type ListSessionTenantsRow struct {
	TenantID    pgtype.UUID
	Slug        string
	DisplayName string
	Status      string
	StarterRole string
}

func (q *Queries) ListSessionTenants(ctx context.Context, sessionTokenHash []byte) ([]ListSessionTenantsRow, error) {
	rows, err := q.db.Query(ctx, listSessionTenants, sessionTokenHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSessionTenantsRow{}
	for rows.Next() {
		var i ListSessionTenantsRow
		if err := rows.Scan(
			&i.TenantID,
			&i.Slug,
			&i.DisplayName,
			&i.Status,
			&i.StarterRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeSession = `-- name: RevokeSession :exec
SELECT iam.revoke_session($1::bytea)
`

func (q *Queries) RevokeSession(ctx context.Context, sessionTokenHash []byte) error {
	_, err := q.db.Exec(ctx, revokeSession, sessionTokenHash)
	return err
}

const rotateSession = `-- name: RotateSession :one
SELECT
  rotated_session.id::uuid AS id,
  rotated_session.subject_id::uuid AS subject_id,
  rotated_session.expires_at::timestamptz AS expires_at,
  rotated_session.rotated_at::timestamptz AS rotated_at
FROM iam.rotate_session(
  $1::bytea,
  $2::bytea,
  $3::bytea
) AS rotated_session(
  id,
  subject_id,
  expires_at,
  rotated_at
)
`

type RotateSessionParams struct {
	SessionTokenHash    []byte
	NewSessionTokenHash []byte
	NewCsrfTokenHash    []byte
}

type RotateSessionRow struct {
	ID        pgtype.UUID
	SubjectID pgtype.UUID
	ExpiresAt pgtype.Timestamptz
	RotatedAt pgtype.Timestamptz
}

func (q *Queries) RotateSession(ctx context.Context, arg RotateSessionParams) (RotateSessionRow, error) {
	row := q.db.QueryRow(ctx, rotateSession, arg.SessionTokenHash, arg.NewSessionTokenHash, arg.NewCsrfTokenHash)
	var i RotateSessionRow
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.ExpiresAt,
		&i.RotatedAt,
	)
	return i, err
}

const switchSessionContext = `-- name: SwitchSessionContext :one
SELECT
  switched_session.session_id::uuid AS session_id,
  switched_session.active_tenant_id::uuid AS active_tenant_id,
  switched_session.active_workspace_id::uuid AS active_workspace_id,
  switched_session.expires_at::timestamptz AS expires_at
FROM iam.switch_session_context(
  $1::bytea,
  $2::bytea,
  $3::bytea,
  $4::uuid,
  $5::uuid
) AS switched_session(
  session_id,
  active_tenant_id,
  active_workspace_id,
  expires_at
)
`

type SwitchSessionContextParams struct {
	CurrentSessionTokenHash     []byte
	ReplacementSessionTokenHash []byte
	ReplacementCsrfTokenHash    []byte
	TargetTenantID              pgtype.UUID
	TargetWorkspaceID           pgtype.UUID
}

type SwitchSessionContextRow struct {
	SessionID         pgtype.UUID
	ActiveTenantID    pgtype.UUID
	ActiveWorkspaceID pgtype.UUID
	ExpiresAt         pgtype.Timestamptz
}

func (q *Queries) SwitchSessionContext(ctx context.Context, arg SwitchSessionContextParams) (SwitchSessionContextRow, error) {
	row := q.db.QueryRow(ctx, switchSessionContext,
		arg.CurrentSessionTokenHash,
		arg.ReplacementSessionTokenHash,
		arg.ReplacementCsrfTokenHash,
		arg.TargetTenantID,
		arg.TargetWorkspaceID,
	)
	var i SwitchSessionContextRow
	err := row.Scan(
		&i.SessionID,
		&i.ActiveTenantID,
		&i.ActiveWorkspaceID,
		&i.ExpiresAt,
	)
	return i, err
}

const upsertSubject = `-- name: UpsertSubject :one
SELECT iam.upsert_subject(
  $1::uuid,
  $2::text,
  $3::text
)::uuid AS subject_id
`

type UpsertSubjectParams struct {
	SubjectID       pgtype.UUID
	ExternalSubject string
	DisplayName     string
}

func (q *Queries) UpsertSubject(ctx context.Context, arg UpsertSubjectParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, upsertSubject, arg.SubjectID, arg.ExternalSubject, arg.DisplayName)
	var subject_id pgtype.UUID
	err := row.Scan(&subject_id)
	return subject_id, err
}
