// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
SELECT iam.create_session(
  $1::uuid,
  $2::uuid,
  $3::bytea,
  $4::bytea,
  $5::timestamptz
)::uuid AS session_id
`

type CreateSessionParams struct {
	SessionID        pgtype.UUID
	SubjectID        pgtype.UUID
	SessionTokenHash []byte
	CsrfTokenHash    []byte
	ExpiresAt        pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.SessionID,
		arg.SubjectID,
		arg.SessionTokenHash,
		arg.CsrfTokenHash,
		arg.ExpiresAt,
	)
	var session_id pgtype.UUID
	err := row.Scan(&session_id)
	return session_id, err
}

const getActiveSession = `-- name: GetActiveSession :one
SELECT
  active_session.id::uuid AS id,
  active_session.subject_id::uuid AS subject_id,
  active_session.csrf_token_hash::bytea AS csrf_token_hash,
  active_session.active_tenant_id::uuid AS active_tenant_id,
  active_session.active_workspace_id::uuid AS active_workspace_id,
  active_session.expires_at::timestamptz AS expires_at,
  active_session.rotated_at::timestamptz AS rotated_at
FROM iam.get_active_session($1::bytea) AS active_session(
  id,
  subject_id,
  csrf_token_hash,
  active_tenant_id,
  active_workspace_id,
  expires_at,
  rotated_at
)
`

type GetActiveSessionRow struct {
	ID                pgtype.UUID
	SubjectID         pgtype.UUID
	CsrfTokenHash     []byte
	ActiveTenantID    pgtype.UUID
	ActiveWorkspaceID pgtype.UUID
	ExpiresAt         pgtype.Timestamptz
	RotatedAt         pgtype.Timestamptz
}

func (q *Queries) GetActiveSession(ctx context.Context, sessionTokenHash []byte) (GetActiveSessionRow, error) {
	row := q.db.QueryRow(ctx, getActiveSession, sessionTokenHash)
	var i GetActiveSessionRow
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.CsrfTokenHash,
		&i.ActiveTenantID,
		&i.ActiveWorkspaceID,
		&i.ExpiresAt,
		&i.RotatedAt,
	)
	return i, err
}

const revokeSession = `-- name: RevokeSession :exec
SELECT iam.revoke_session($1::bytea)
`

func (q *Queries) RevokeSession(ctx context.Context, sessionTokenHash []byte) error {
	_, err := q.db.Exec(ctx, revokeSession, sessionTokenHash)
	return err
}

const upsertSubject = `-- name: UpsertSubject :one
SELECT iam.upsert_subject(
  $1::uuid,
  $2::text,
  $3::text
)::uuid AS subject_id
`

type UpsertSubjectParams struct {
	SubjectID       pgtype.UUID
	ExternalSubject string
	DisplayName     string
}

func (q *Queries) UpsertSubject(ctx context.Context, arg UpsertSubjectParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, upsertSubject, arg.SubjectID, arg.ExternalSubject, arg.DisplayName)
	var subject_id pgtype.UUID
	err := row.Scan(&subject_id)
	return subject_id, err
}
