// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// Immutable signed attestations of audit-chain prefixes. Signature keys are external; only bounded key identifiers and signatures are stored.
type AuditCheckpoint struct {
	TenantID        pgtype.UUID
	ID              pgtype.UUID
	ChainSequence   int64
	ChainHash       []byte
	StatementDigest []byte
	Algorithm       string
	KeyID           string
	Signature       []byte
	SignedAt        pgtype.Timestamptz
}

type IamMembership struct {
	TenantID    pgtype.UUID
	SubjectID   pgtype.UUID
	StarterRole string
	Status      string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type IamPreference struct {
	TenantID    pgtype.UUID
	SubjectID   pgtype.UUID
	Theme       string
	Locale      string
	Preferences []byte
	UpdatedAt   pgtype.Timestamptz
}

type IamTenant struct {
	ID          pgtype.UUID
	Slug        string
	DisplayName string
	Status      string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type IamWorkspace struct {
	TenantID    pgtype.UUID
	ID          pgtype.UUID
	Slug        string
	DisplayName string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}
