// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: operations.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimIdempotencyKey = `-- name: ClaimIdempotencyKey :one
SELECT
  claim.claim_state::text AS claim_state,
  COALESCE(claim.response_status, 0)::integer AS response_status,
  claim.response_body::jsonb AS response_body,
  claim.correlation_id::uuid AS correlation_id
FROM ops.claim_idempotency_key(
  $1::text,
  $2::text,
  $3::text,
  $4::uuid,
  $5::timestamptz
) AS claim(
  claim_state,
  response_status,
  response_body,
  correlation_id
)
`

type ClaimIdempotencyKeyParams struct {
	IdempotencyKey string
	Operation      string
	RequestHash    string
	CorrelationID  pgtype.UUID
	ExpiresAt      pgtype.Timestamptz
}

type ClaimIdempotencyKeyRow struct {
	ClaimState     string
	ResponseStatus int32
	ResponseBody   []byte
	CorrelationID  pgtype.UUID
}

func (q *Queries) ClaimIdempotencyKey(ctx context.Context, arg ClaimIdempotencyKeyParams) (ClaimIdempotencyKeyRow, error) {
	row := q.db.QueryRow(ctx, claimIdempotencyKey,
		arg.IdempotencyKey,
		arg.Operation,
		arg.RequestHash,
		arg.CorrelationID,
		arg.ExpiresAt,
	)
	var i ClaimIdempotencyKeyRow
	err := row.Scan(
		&i.ClaimState,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.CorrelationID,
	)
	return i, err
}

const completeIdempotencyKey = `-- name: CompleteIdempotencyKey :one
SELECT ops.complete_idempotency_key(
  $1::text,
  $2::text,
  $3::text,
  $4::integer,
  $5::jsonb
)::boolean AS completed
`

type CompleteIdempotencyKeyParams struct {
	IdempotencyKey string
	Operation      string
	RequestHash    string
	ResponseStatus int32
	ResponseBody   []byte
}

func (q *Queries) CompleteIdempotencyKey(ctx context.Context, arg CompleteIdempotencyKeyParams) (bool, error) {
	row := q.db.QueryRow(ctx, completeIdempotencyKey,
		arg.IdempotencyKey,
		arg.Operation,
		arg.RequestHash,
		arg.ResponseStatus,
		arg.ResponseBody,
	)
	var completed bool
	err := row.Scan(&completed)
	return completed, err
}
