// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateMembership(ctx context.Context, arg CreateMembershipParams) (IamMembership, error)
	CreateTenant(ctx context.Context, arg CreateTenantParams) (IamTenant, error)
	CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (IamWorkspace, error)
	GetMembership(ctx context.Context, arg GetMembershipParams) (IamMembership, error)
	GetPreference(ctx context.Context, arg GetPreferenceParams) (IamPreference, error)
	GetTenant(ctx context.Context, tenantID pgtype.UUID) (IamTenant, error)
	GetWorkspace(ctx context.Context, arg GetWorkspaceParams) (IamWorkspace, error)
	ListWorkspaces(ctx context.Context, tenantID pgtype.UUID) ([]IamWorkspace, error)
	UpsertPreference(ctx context.Context, arg UpsertPreferenceParams) (IamPreference, error)
}

var _ Querier = (*Queries)(nil)
