// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenant_switch.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bindTenantSwitchIdempotency = `-- name: BindTenantSwitchIdempotency :one
SELECT
  bind.mapping_state::text AS mapping_state,
  bind.session_id::uuid AS session_id,
  bind.generation::bigint AS generation,
  bind.active_tenant_id::uuid AS active_tenant_id,
  bind.active_workspace_id::uuid AS active_workspace_id,
  bind.session_expires_at::timestamptz AS session_expires_at,
  bind.receipt_expires_at::timestamptz AS receipt_expires_at,
  bind.receipt_hash::text AS receipt_hash
FROM iam.bind_tenant_switch_idempotency(
  $1::bytea,
  $2::text,
  $3::text,
  $4::uuid
) AS bind(
  mapping_state,
  session_id,
  generation,
  active_tenant_id,
  active_workspace_id,
  session_expires_at,
  receipt_expires_at,
  receipt_hash
)
`

type BindTenantSwitchIdempotencyParams struct {
	CurrentSessionTokenHash []byte
	IdempotencyKey          string
	RequestHash             string
	TargetTenantID          pgtype.UUID
}

type BindTenantSwitchIdempotencyRow struct {
	MappingState      string
	SessionID         pgtype.UUID
	Generation        int64
	ActiveTenantID    pgtype.UUID
	ActiveWorkspaceID pgtype.UUID
	SessionExpiresAt  pgtype.Timestamptz
	ReceiptExpiresAt  pgtype.Timestamptz
	ReceiptHash       string
}

func (q *Queries) BindTenantSwitchIdempotency(ctx context.Context, arg BindTenantSwitchIdempotencyParams) (BindTenantSwitchIdempotencyRow, error) {
	row := q.db.QueryRow(ctx, bindTenantSwitchIdempotency,
		arg.CurrentSessionTokenHash,
		arg.IdempotencyKey,
		arg.RequestHash,
		arg.TargetTenantID,
	)
	var i BindTenantSwitchIdempotencyRow
	err := row.Scan(
		&i.MappingState,
		&i.SessionID,
		&i.Generation,
		&i.ActiveTenantID,
		&i.ActiveWorkspaceID,
		&i.SessionExpiresAt,
		&i.ReceiptExpiresAt,
		&i.ReceiptHash,
	)
	return i, err
}

const finishTenantSwitchIdempotency = `-- name: FinishTenantSwitchIdempotency :one
SELECT
  finished::boolean AS finished,
  session_id::uuid AS session_id,
  result_generation::bigint AS result_generation
FROM iam.finish_tenant_switch_idempotency(
  $1::bytea,
  $2::text,
  $3::text
) AS finished_scope(
  finished,
  session_id,
  result_generation
)
`

type FinishTenantSwitchIdempotencyParams struct {
	CurrentSessionTokenHash []byte
	IdempotencyKey          string
	RequestHash             string
}

type FinishTenantSwitchIdempotencyRow struct {
	Finished         bool
	SessionID        pgtype.UUID
	ResultGeneration int64
}

func (q *Queries) FinishTenantSwitchIdempotency(ctx context.Context, arg FinishTenantSwitchIdempotencyParams) (FinishTenantSwitchIdempotencyRow, error) {
	row := q.db.QueryRow(ctx, finishTenantSwitchIdempotency, arg.CurrentSessionTokenHash, arg.IdempotencyKey, arg.RequestHash)
	var i FinishTenantSwitchIdempotencyRow
	err := row.Scan(&i.Finished, &i.SessionID, &i.ResultGeneration)
	return i, err
}
