// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenant_switch_response.sql

package sqlcgen

import (
	"context"
)

const getTenantSwitchResponseETag = `-- name: GetTenantSwitchResponseETag :one
SELECT ops.get_tenant_switch_response_etag(
  $1::text,
  $2::text
)::text AS response_etag
`

type GetTenantSwitchResponseETagParams struct {
	IdempotencyKey string
	RequestHash    string
}

func (q *Queries) GetTenantSwitchResponseETag(ctx context.Context, arg GetTenantSwitchResponseETagParams) (string, error) {
	row := q.db.QueryRow(ctx, getTenantSwitchResponseETag, arg.IdempotencyKey, arg.RequestHash)
	var i string
	err := row.Scan(&i)
	return i, err
}

const setTenantSwitchResponseETag = `-- name: SetTenantSwitchResponseETag :one
SELECT ops.set_tenant_switch_response_etag(
  $1::text,
  $2::text,
  $3::text
)::boolean AS set_response_etag
`

type SetTenantSwitchResponseETagParams struct {
	IdempotencyKey string
	RequestHash    string
	ResponseETag   string
}

func (q *Queries) SetTenantSwitchResponseETag(ctx context.Context, arg SetTenantSwitchResponseETagParams) (bool, error) {
	row := q.db.QueryRow(ctx, setTenantSwitchResponseETag, arg.IdempotencyKey, arg.RequestHash, arg.ResponseETag)
	var i bool
	err := row.Scan(&i)
	return i, err
}
