// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenancy.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptInvitation = `-- name: AcceptInvitation :one
SELECT tenant_id::uuid AS tenant_id,
       subject_id::uuid AS subject_id,
       starter_role::text AS starter_role,
       status::text AS status
FROM iam.accept_invitation(
  $1::bytea,
  $2::uuid
)
`

type AcceptInvitationParams struct {
	TokenHash []byte
	SubjectID pgtype.UUID
}

type AcceptInvitationRow struct {
	TenantID    pgtype.UUID
	SubjectID   pgtype.UUID
	StarterRole string
	Status      string
}

func (q *Queries) AcceptInvitation(ctx context.Context, arg AcceptInvitationParams) (AcceptInvitationRow, error) {
	row := q.db.QueryRow(ctx, acceptInvitation, arg.TokenHash, arg.SubjectID)
	var i AcceptInvitationRow
	err := row.Scan(
		&i.TenantID,
		&i.SubjectID,
		&i.StarterRole,
		&i.Status,
	)
	return i, err
}

const createMembership = `-- name: CreateMembership :one
INSERT INTO iam.memberships (tenant_id, subject_id, starter_role, status)
VALUES ($1, $2, $3, 'active')
RETURNING tenant_id, subject_id, starter_role, status, created_at, updated_at
`

type CreateMembershipParams struct {
	TenantID    pgtype.UUID
	SubjectID   pgtype.UUID
	StarterRole string
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) (IamMembership, error) {
	row := q.db.QueryRow(ctx, createMembership, arg.TenantID, arg.SubjectID, arg.StarterRole)
	var i IamMembership
	err := row.Scan(
		&i.TenantID,
		&i.SubjectID,
		&i.StarterRole,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTenant = `-- name: CreateTenant :one
INSERT INTO iam.tenants (id, slug, display_name, status)
VALUES ($1, $2, $3, 'active')
RETURNING id, slug, display_name, status, created_at, updated_at
`

type CreateTenantParams struct {
	TenantID    pgtype.UUID
	Slug        string
	DisplayName string
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (IamTenant, error) {
	row := q.db.QueryRow(ctx, createTenant, arg.TenantID, arg.Slug, arg.DisplayName)
	var i IamTenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO iam.workspaces (tenant_id, id, slug, display_name)
VALUES ($1, $2, $3, $4)
RETURNING tenant_id, id, slug, display_name, created_at, updated_at
`

type CreateWorkspaceParams struct {
	TenantID    pgtype.UUID
	WorkspaceID pgtype.UUID
	Slug        string
	DisplayName string
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (IamWorkspace, error) {
	row := q.db.QueryRow(ctx, createWorkspace,
		arg.TenantID,
		arg.WorkspaceID,
		arg.Slug,
		arg.DisplayName,
	)
	var i IamWorkspace
	err := row.Scan(
		&i.TenantID,
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActivePolicySnapshot = `-- name: GetActivePolicySnapshot :one
SELECT version, snapshot_hash
FROM authz.policy_snapshots
WHERE tenant_id = $1
  AND status = 'active'
ORDER BY version DESC
LIMIT 1
`

type GetActivePolicySnapshotRow struct {
	Version      int64
	SnapshotHash string
}

func (q *Queries) GetActivePolicySnapshot(ctx context.Context, tenantID pgtype.UUID) (GetActivePolicySnapshotRow, error) {
	row := q.db.QueryRow(ctx, getActivePolicySnapshot, tenantID)
	var i GetActivePolicySnapshotRow
	err := row.Scan(&i.Version, &i.SnapshotHash)
	return i, err
}

const getMembership = `-- name: GetMembership :one
SELECT tenant_id, subject_id, starter_role, status, created_at, updated_at
FROM iam.memberships
WHERE tenant_id = $1
  AND subject_id = $2
`

type GetMembershipParams struct {
	TenantID  pgtype.UUID
	SubjectID pgtype.UUID
}

func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (IamMembership, error) {
	row := q.db.QueryRow(ctx, getMembership, arg.TenantID, arg.SubjectID)
	var i IamMembership
	err := row.Scan(
		&i.TenantID,
		&i.SubjectID,
		&i.StarterRole,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPreference = `-- name: GetPreference :one
SELECT tenant_id, subject_id, theme, locale, preferences, updated_at
FROM iam.preferences
WHERE tenant_id = $1
  AND subject_id = $2
`

type GetPreferenceParams struct {
	TenantID  pgtype.UUID
	SubjectID pgtype.UUID
}

func (q *Queries) GetPreference(ctx context.Context, arg GetPreferenceParams) (IamPreference, error) {
	row := q.db.QueryRow(ctx, getPreference, arg.TenantID, arg.SubjectID)
	var i IamPreference
	err := row.Scan(
		&i.TenantID,
		&i.SubjectID,
		&i.Theme,
		&i.Locale,
		&i.Preferences,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenant = `-- name: GetTenant :one
SELECT id, slug, display_name, status, created_at, updated_at
FROM iam.tenants
WHERE id = $1
`

func (q *Queries) GetTenant(ctx context.Context, tenantID pgtype.UUID) (IamTenant, error) {
	row := q.db.QueryRow(ctx, getTenant, tenantID)
	var i IamTenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspace = `-- name: GetWorkspace :one
SELECT tenant_id, id, slug, display_name, created_at, updated_at
FROM iam.workspaces
WHERE tenant_id = $1
  AND id = $2
`

type GetWorkspaceParams struct {
	TenantID    pgtype.UUID
	WorkspaceID pgtype.UUID
}

func (q *Queries) GetWorkspace(ctx context.Context, arg GetWorkspaceParams) (IamWorkspace, error) {
	row := q.db.QueryRow(ctx, getWorkspace, arg.TenantID, arg.WorkspaceID)
	var i IamWorkspace
	err := row.Scan(
		&i.TenantID,
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWorkspaces = `-- name: ListWorkspaces :many
SELECT tenant_id, id, slug, display_name, created_at, updated_at
FROM iam.workspaces
WHERE tenant_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListWorkspaces(ctx context.Context, tenantID pgtype.UUID) ([]IamWorkspace, error) {
	rows, err := q.db.Query(ctx, listWorkspaces, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IamWorkspace{}
	for rows.Next() {
		var i IamWorkspace
		if err := rows.Scan(
			&i.TenantID,
			&i.ID,
			&i.Slug,
			&i.DisplayName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPreference = `-- name: UpsertPreference :one
INSERT INTO iam.preferences (tenant_id, subject_id, theme, locale, preferences, updated_at)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  now()
)
ON CONFLICT (tenant_id, subject_id) DO UPDATE
SET theme = EXCLUDED.theme,
    locale = EXCLUDED.locale,
    preferences = EXCLUDED.preferences,
    updated_at = now()
RETURNING tenant_id, subject_id, theme, locale, preferences, updated_at
`

type UpsertPreferenceParams struct {
	TenantID    pgtype.UUID
	SubjectID   pgtype.UUID
	Theme       string
	Locale      string
	Preferences []byte
}

func (q *Queries) UpsertPreference(ctx context.Context, arg UpsertPreferenceParams) (IamPreference, error) {
	row := q.db.QueryRow(ctx, upsertPreference,
		arg.TenantID,
		arg.SubjectID,
		arg.Theme,
		arg.Locale,
		arg.Preferences,
	)
	var i IamPreference
	err := row.Scan(
		&i.TenantID,
		&i.SubjectID,
		&i.Theme,
		&i.Locale,
		&i.Preferences,
		&i.UpdatedAt,
	)
	return i, err
}
